-- GENERATED by C->Haskell Compiler, version 0.16.0 Crystal Seed, 24 Jan 2009 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "HOpenCV.chs" #-}{-# LANGUAGE ForeignFunctionInterface #-}


module HOpenCV where 

import Foreign.C.Types
import Foreign.Ptr
import Foreign.Storable

import C2HS

type IplImage = Ptr (())
{-# LINE 13 "HOpenCV.chs" #-}
type CvCapture = Ptr (())
{-# LINE 14 "HOpenCV.chs" #-}

newCapture :: Int -> IO (CvCapture)
newCapture a1 =
  let {a1' = fromIntegral a1} in 
  newCapture'_ a1' >>= \res ->
  let {res' = id res} in
  return (res')
{-# LINE 17 "HOpenCV.chs" #-}

--{#fun del_capture as ^
--      {id `PCvCapture'} -> `()' id#}

queryFrame :: CvCapture -> IO (IplImage)
queryFrame a1 =
  let {a1' = id a1} in 
  queryFrame'_ a1' >>= \res ->
  let {res' = id res} in
  return (res')
{-# LINE 23 "HOpenCV.chs" #-}

main :: IO ()
main = do
  capture <- newCapture 0
  frame <- queryFrame capture
  return ()


foreign import ccall safe "HOpenCV.chs.h new_capture"
  newCapture'_ :: (CInt -> (IO (CvCapture)))

foreign import ccall safe "HOpenCV.chs.h query_frame"
  queryFrame'_ :: ((CvCapture) -> (IO (IplImage)))
